name: Autograding Tests
'on':
- push
- repository_dispatch
permissions:
  checks: write
  actions: read
  contents: read
jobs:
  run-autograding-tests:
    runs-on: ubuntu-latest
    if: github.actor != 'github-classroom[bot]'
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    - name: ejercicio test
      id: ejercicio-test
      uses: classroom-resources/autograding-io-grader@v1
      with:
        test-name: ejercicio test
        setup-command: ''
        command: "./ejercicio1_test.py"
        input: ''
        expected-output: ''
        comparison-method: exact
        timeout: 5
        max-score: 5
    - name: Autograding Reporter
      uses: classroom-resources/autograding-grading-reporter@v1
      env:
        EJERCICIO-TEST_RESULTS: "${{steps.ejercicio-test.outputs.result}}"
      with:
        runners: ejercicio-test
